### ISSUE TITLE
Error when connect da2 in my own laptop

### ISSUE THREAD

**Issue by GaoKai1537** [ssc-oscar/DRE#32]
I am following [Setup Instructions Option A](https://github.com/ssc-oscar/DRE#setup-instructions-option-a). But in step 5: From your own laptop open terminal and run (my netid is kgao and my port is 9299), I get the following error: 
```bash
ssh -p9299 -L3001:localhost:443 -L3000:localhost:3000 -L3002:localhost:80 kgao@da2.eecs.utk.edu -i ~/.ssh/id_rsa                                                                                                                    
kgao@da2.eecs.utk.edu's password:
```
I can only login da server via public key. 
I also tried to log in da2 server, still failed:
```bash
ssh -p 443 kgao@da2.eecs.utk.edu -i ~/.ssh/id_rsa                                                                                                                                                                      
ssh: connect to host da2.eecs.utk.edu port 443: Connection refused
```
But I can log in da0 server successfully!

**Comment by audrism** [comment]
Yes, the containers use ldap, while i add external users via yp. 
For some reason ypbind does not seem to work from inside the container. I'll see if I can fix it.

da2 runs https, so ssh is on port 22. 

You can login to da2 via port 22 and exec into container.  If you open some high port on the container that might work. 

You can also run container on d0 or other server. All you need is connect to npm inside the container.

**Comment by audrism** [comment]
To start the container a number of steps are neede, but you can update things easily afterwards:

```
ssh -p443 -L3000:localhost:3000 kgao@da3.eecs.utk.edu
tmux
docker run -it -v /home/kgao:/home/kgao -w /home/kgao -p3000:3000 swsc/mern bash
echo "kgao:x:5002:5002::/home/kgao:/bin/bash" >> /etc/passwd
echo "kgao:x:5002:" >> /etc/group
ssh-keygen
cat /root/.ssh/id_rsa.pub > /tmp/a
su - kgao 
cat /tmp/a >> /home/kgao/.ssh/autohrized_keys
exit
ssh kgao@da4
exit
cp -pr DRE /opt/
cd /opt/DRE
npm install
export DRE_LOOKUP_PATH=/home/kgao/lookup
export DRE_REMOTE_CMD='ssh -T kgao@da4' 
npm run start:dev
```
