### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Maze-Mind** [ssc-oscar/DRE#39]
The website has been down since you merged my pull request. Is there anything that I need to fix to get it back up again? @audrism

**Comment by audrism** [comment]
Seems to be working for me: do you mean https://worldofcode.org?

**Comment by Maze-Mind** [comment]
Oh, it doesn't work with "www.worldofcode.org" anymore, but it does with that link.

**Comment by Maze-Mind** [comment]
When you use that link it gives a "Connection is not private" warning. Bogdan is concerned that people won't use the site because of this. Check slack to see the conversation

**Comment by audrism** [comment]
This is because of the certificate. There is a way to set it up, but the previpus expired: can you take a look at that?

**Comment by Maze-Mind** [comment]
Yeah, I'll look into it.

**Comment by audrism** [comment]
1. turn off server

2. certbot certonly --standalone

3. make sure server/server.js has
```
  https.createServer({
     key: fs.readFileSync('/etc/letsencrypt/live/worldofcode.org/privkey.pem'),
     cert: fs.readFileSync('/etc/letsencrypt/live/worldofcode.org/cert.pem'),
     ca: fs.readFileSync('/etc/letsencrypt/live/worldofcode.org/chain.pem')
   }, app).listen(443, (err) => {
```
These might get renamed to hostname, so I fixed them back.

4. restart the server

npm run start:prod


Make sure environment is set:
DRE_LOOKUP_PATH=/home/audris/lookup
DRE_REMOTE_CMD=ssh -T akarnauc@da0

**Comment by audrism** [comment]
certbot certonly --standalone
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel): worldofcode.org
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for worldofcode.org
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/worldofcode.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/worldofcode.org/privkey.pem
   Your cert will expire on 2021-05-13. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

**Comment by audrism** [comment]
Now that the server is running on user port: need to configure certbot to server challenge on that port

**Comment by audrism** [comment]
- Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/worldofcode.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/worldofcode.org/privkey.pem
   Your cert will expire on 2021-11-10. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:
