### ISSUE TITLE
unknown password to docker container

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/DRE#62]
@audrism I started my docker container after it was closed by the maintenance the other day and when I try to access it, it asks for a password that I do not know. This has happened before and I remember you clearing it for me then, so if you could do that again I would appreciate it.

**Comment by audrism** [comment]
Rm /var/run/sssd.pid and restart sssd as o /bin/startsvc.sh

**Comment by dlomax64** [comment]
Having this issue again. I tried doing the commands that you listed but I don't have the permissions.

**Comment by audrism** [comment]
```
ssh da2
docker exec -it mernDylan bash
rm /var/run/sssd.pid
/usr/sbin/sssd -fd 2
```

**Comment by dlomax64** [comment]
All good now
