### ISSUE TITLE
MongoDB errors

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/DRE#80]
@audrism The changes that you made to the Mongo config are not working on my end.

![image](https://user-images.githubusercontent.com/53716031/152254802-dfc80f36-6e06-4923-978e-3a69db70a17d.png)

Do you know the solution to this?

**Comment by audrism** [comment]
When starting docker need option to link to database in another docker container

--link dbWoC:dbWoC

**Comment by dlomax64** [comment]
Do I need to make a new one with that flag then? Or is there a way to apply it to the one I already made?

**Comment by audrism** [comment]
You'll need to restart or change the database url (now da1 has mongodb5 which should work)

**Comment by audrism** [comment]
i.e., instead of dbwoc use gda1

**Comment by dlomax64** [comment]
Adding the link flag fixed it. I'll add that to the setup documentation
